config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'pages#about'
  get '/community', to: 'pages#community'
  get '/home', to: 'pages#home'

  # devise_for :users
devise_for :users, controllers: {
   sessions: 'users/sessions'
}
# resources :users, :only => [:show]

root to: 'events#index'

resources :events do
  resources :locations do
  end
end

resources :users do
  resources :events do
  end
end

post '/locations', to: 'locations#create'
get '/locations', to: "locations#show"
get '/locations/:id', to: "locations#showOne"
#  post '/users', to: 'users#create'
# get 'users/:id', to: "users#show"
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :events

	geocoded_by :address,
  		:latitude => :lat, :longitude => :lng
		after_validation :geocode

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :showOne]
	def show
		@locations = Location.all 
	end

	def new
		@location = Location.new
	end

	def create
		location_params = params.require(:location).permit(:name, :address, :image)
		@location = Location.create(location_params)
		redirect_to "/events/new"
	end

	def showOne
		@location = Location.find(params[:id])
		@events = Event.where(:location_id => @location.id)
	end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/show.html.erb
<style> 
body, input{
	font-family: 'Montserrat', sans-serif;
	font-size: 18px;
	background-color: none;
}
<<<<<<< HEAD
h1{
	font-family: 'Montserrat', sans-serif;
	font-size: 50px;
	padding-bottom: 20px;
}

=======
>>>>>>> 4e4acd2d37cf8bd1c55bdf09e90a48708bf9ad49
h2{
	font-family: 'Montserrat', sans-serif;
	font-size: 30px;
	padding-bottom: 20px;
	position: center;
}
p2{
	font-family: 'Lora', serif;
	color: #5b5b5b;
}
em {
	font-family: 'Montserrat', sans-serif;
	font-size: 13px;
}
/*SECTION*/
section{
	background-color: #fff;
	padding: 80px 0;
}
section.darker{
	background-color: #fbfbfb;
}
section header{
	text-align: center;
	margin-bottom: 80px;
}
address{
	margin-bottom: 50px;
}
address span{
	margin-top:0;
	margin-bottom: 25px;
	font-size: 20px;
	display: block;
}
a{
	color: white;
	text-transform: uppercase;
}
a:hover,
a:focus{
	color: #A9B262;
}
.container {
	padding-top: 0px;
	padding-right: 15px;
	padding-left: 15px;
	margin-right: auto;
	margin-left: auto;
}  
.container-location {
	width: 1170px;
	padding-top: 0px;
	padding-right: 15px;
	padding-left: 15px;
	margin-right: auto;
	margin-left: auto;
}
.row {
	margin-right: -15px;
	margin-left: -15px;
}

.logo{
	background: url('./logo.png');
	position: absolute;
	left: 15px;
	top: 15px;
	width: 385px;
	height: 90px;
}

.fa{ 
	color: white;
}
.fa-close{
	color: #A9B262;
}
.menu-toggle{
	position: absolute;
	right: 15px;
	top: 15px;
	font-size: 30px;
	color: #fff;
}
.menu{
	width: 300px;
	display: block;
	background: #333;
	height: 100%;
	top: 0;
	right: -300px;
	position: fixed;
	z-index: 100;
	text-align: center;
	transition: right 0.4s;
}
.menu.nav-expanded{
	right: 0;
}
.menu .close{
	color: #fff;
	margin-right: 10px;
	margin-top:10px;
}
.menu h3{
	margin-top:50px;
	text-transform: uppercase;
}
.menu .nav{
	padding: 0;
}
.menu .nav > li > a{
	color: #fff;
}
.menu .nav > li > a:hover,
.menu .nav > li > a:focus{
	background: transparent;
	color: #A9B262;
}
/* Backgrounds */
#banner {
	background-attachment: scroll, scroll, scroll, fixed;
	background-image: url('home-bg.jpg');
	background-position: 100%;
	background-repeat: no-repeat, no-repeat, repeat, no-repeat;
	background-size: cover;
	width: 100%;
	height: 700px;
	color: white;
	cursor: default;
	text-align: center;
}
#banner-location {
	background: url('location-bg.jpg') no-repeat center fixed;
	background-position: 100%;
	background-size: cover;
	width: 100%;
	height: 100%;

}
/* Images */
img{
	-webkit-filter: sepia(70%);
	top:0;
	left: 15px;
	right: 15px;
	height: 257px;
	width: 360px;
	vertical-align: middle;
}
/* Location */
.location-item{
	position: relative;
	margin-bottom: 30px;
}
.location-item .mask{
	position: absolute;
	top:0;
	height: 257px;
	width: 360px;
	transition: all 0.4s;
	background: rgba(0,0,0, 0.5);
	opacity: 0;
}
.location-item .figcaption.mask i{
	position: absolute;
	height: 257px;
	width: 360px;
	color: #fff;
	background-color: #A9B262;
}
.location-item:hover .mask{
	opacity: 1;
}
.maskpadding {
	height: 257px;
	width: 360px;
	padding: 40px;
}
m1 {
	font-family: 'Montserrat', sans-serif;
	font-size: 22px;
	color: #fff;
	position: center;
}
m2 {
	font-family: 'Lora', serif;
	font-size: 16px;
	color: #fff;
	position: center;
    
}
  #banner-location {
  	background:url(/assets/location-bg.jpg) fixed repeat;
    background-position: 100%;
    background-size: cover;
    width: 100%;
	height: 3000px;
   
 }
</style>

<section id= "banner-location"> 
	<header>
	<h2>Locations</h2>
	<p2>WHAT HAPPENED IN YOUR LOCATION.</p2>
	</header>
<div class="container-location">



			<% @locations.each do |l| %>


			<figure class="location-item col-md-4 col-sm-6" >

			<img src="/assets/<%= l.image %>" > </img>

			<figcaption class="mask">
			<div class= "maskpadding">
			<div class= "text-center">

				<m1><%= l.name %></m1><br>
				<m2><%= l.address %><br>
				Latitude: <%= l.lat %><br>
				Longitude: <%= l.lng %><br>
				Location added: <%= l.created_at.strftime('%c') %></m2>
			</div>	
				</figcaption>
			</figure>

<% end %>

</div>

</section>

app/views/locations/showOne.html.erb
<section id= "banner-paper"> 

<style type="text/css">
    h3, a{font-family: 'Playfair Display', serif; color: black}
}
h2{font-family: 'Playfair Display SC', serif; font-weight: bold}
hr{    
	border: 0;
    border-bottom: 1px double #8E1F1D;;}
.rotate2 {
    transform: rotate(90deg);
    transition: .3s;
}
.everything{
	background-color: #F2C8B2;
	padding: 80px;
	border: double 5px ;

  background: 
    linear-gradient(
      rgba(242, 200, 178, 0.6),
      rgba(242, 200, 178, 0.7)
    ),
    url(/assets/paper-bg.jpg);
}

</style>
<div class="col-md-2"></div>
<div class="everything col-md-8">
<h3>What happened in ... </h3>
<h2><%= @location.name %>?</h2>

<hr>
	<% @events.each do |event| %>
        <div class="collapse-group"><a class="expand" href="#">
          <h4><%= event.date.year %> - <u><%= event.title %></u>

          <img class="hand" src="/assets/pointingright.png" width="30"></a></h4>
           <p class="collapse"> <%= event.content %> 
           <br>
           Tags:
          <% if event.tag_art == true%>
          &nbspART
          <% end %> 
          <% if event.tag_people == true%>
          &nbspPEOPLE
          <% end %> 
          <% if event.tag_science == true%>
          &nbspSCIENCE
          <% end %> 
          <% if event.tag_politics == true%>
          &nbspPOLITICS
          <% end %> 
          <% if event.tag_conflict == true%>
          &nbspCONFLICT
          <% end %> 
          <% if event.tag_nature == true%>
          &nbspNATURE
          <% end %> <br>
          created at <%= event.created_at.strftime('%c') %><br>
          last updated <%= event.updated_at.strftime('%c') %><br> 


          <% if current_user %>
          <%= link_to "EDIT THIS EVENT", edit_event_path(event) , method: :get, class: "btn button-primary" %>
          <% end %>
      
<% end %>
<hr><a href="#back">Back to Map.</a>
            </div>
            </p>
</p>



</div>
<script type="text/javascript">
$('.expand').on('click', function(e) {
    e.preventDefault();
	$(this).find('.hand').toggleClass('rotate2');

    var $collapse = $(this).closest('.collapse-group').find('.collapse');
    $collapse.collapse('toggle');
});
</script>

</section>