config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'pages#about'
  get '/community', to: 'pages#community'
  get '/home', to: 'pages#home'

  # devise_for :users
devise_for :users, controllers: {
   sessions: 'users/sessions'
}
# resources :users, :only => [:show]

root to: 'events#index'

resources :events do
  resources :locations do
  end
end

resources :users do
  resources :events do
  end
end

post '/locations', to: 'locations#create'
get '/locations', to: "locations#show"
get '/locations/:id', to: "locations#showOne"
#  post '/users', to: 'users#create'
# get 'users/:id', to: "users#show"
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, presence: true
	validates :date, presence: true
  belongs_to :location
  has_many :users, :through => :user_events
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :events

	geocoded_by :address,
  		:latitude => :lat, :longitude => :lng
		after_validation :geocode

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :events
	has_many :events, :through => :user_events


end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate_user!, :except => [:index]

	def index
		@events = Event.all
		@locations = Location.all
		@users = User.all
		gon.locations = @locations


	end

	def new
		@event = Event.new
		@location = Location.new
	end

	def create

		event_params = params.require(:event).permit(:title, :date, :link, :image, :content, :tag_art, :tag_people, :tag_science, :tag_politics, :tag_conflict, :tag_nature, :tag_sports, :location_id)
		@location = event_params[:location_id]
		@event = Event.new(event_params)
		if @event.save
			p @event
		else
			p @event.errors
		end
		redirect_to events_path
		
	end
	def edit
		id = params[:id]
		@event = Event.find(id)
		render :edit
		
	end
	def update
		id = params[:id]
		@event = Event.find(id)
		updated_info = params.require(:event).permit(:title, :date, :link, :image, :content, :tag_art, :tag_people, :tag_science, :tag_politics, :tag_conflict, :tag_nature, :tag_sports, :location_id)
		@event.update_attributes(updated_info)
		redirect_to event_path
	end
	def destroy
		id params[:id]
		@event = Event.find(id)
		@event. destroy
		redirect_to(events_path)
	end
	def show
		@event = Event.find(params[:id])
		@location = Location.where(:event_id => @event.id)
		
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :showOne]
	def show
		@locations = Location.all 
	end

	def new
		@location = Location.new
	end

	def create
		location_params = params.require(:location).permit(:name, :address, :image)
		@location = Location.create(location_params)
		redirect_to "/events/new"
	end

	def showOne
		@location = Location.find(params[:id])
		@events = Event.where(:location_id => @location.id)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
		before_filter :authenticate_user!, :except => [:about, :community, :home]
  def about
  end
  def community
  end
  def home
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@events = Event.all
		current_user
		
	end
	def create
		@user = current_user
		@event = Event.find(params[:event_id])
		@user.events.push(@event)

		redirect_to user_events(@user)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	# before_action :authenticate_user!
before_filter :authenticate_user!, :except => [:new]
def index
		@users = User.all
		gon.users = @users

end

def show
	@user = User.find(params[:id])

end
def edit
		id params[:id]
		@user = User.find(id)
		
		redirect_to(user_path)
end

def showOne
	@user = User.find(params[:id])
end


	# user_signed_in?
	# current_user
	# user_session
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<html lang="en-us">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>It Happened Here</title>

  <!-- Load fonts -->
<link href='https://fonts.googleapis.com/css?family=Playfair+Display+SC' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>
</head>
<body>
<header>
	
		<a href="" class="menu-toggle" id="nav-expander"><i class="fa fa-bars"></i></a>
		<!-- Offsite navigation -->
		<nav class="menu">
			<a href="#" class="close"><i class="fa fa-close"></i></a>
			<h3></h3>
			<ul class="nav">
				<li><%= link_to "HOME", home_path, method: :get%></li>
				<li><%= link_to "MAP", events_path, method: :get%></li>
				<li><%= link_to "LOCATIONS", locations_path, method: :get%> </li>
				<li><%= link_to "COMMUNITY", community_path, method: :get%></li>
				<li><%= link_to "ABOUT", about_path, method: :get%></a></li>
				
				<% if !current_user %>
				<li><%= link_to "SIGN UP", new_user_registration_path, method: :get%></li>
				 <li><%= link_to "LOGIN", new_user_session_path, method: :get%></li>
				<% end %>

				<% if current_user %>
				
				
				<li><%= link_to "USERS", users_path, method: :get%></li>
				<li><%= link_to "EDIT USER", edit_user_registration_path, method: :get%></li>
				<li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %><% end %></li>
			</ul>
			</nav>
			
	</div>


				<% if notice %>
				  <p class="alert alert-success"><%= notice %></p>
				<% end %>
				<% if alert %>
				  <p class="alert alert-danger"><%= alert %></p>
				<% end %>
              
            </ul>
          </nav>
        </div>
      </div>
    </header>
  

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<style type="text/css">
.about, h1{
	font-family: 'Playfair Display', serif;
}
p{
	font-size: 20px;
	color: #444444;
}
li
{
    list-style-type: none;
}
a{color:#999999;}
.hand {margin-right: 10px}</style>

<section id= "banner-paper"> 
<img src="/assets/ihh-logo-black" width="20%"><br><h1>About It Happened Here</h1>
<p>It Happend Here is a mobile focused, community generated web-app to connect people to the history and stories around them. </p><hr>
<img src="/assets/ihh-type.png" width="20%">
<p>Technologies used: <br><br>Ruby on Rails, Git/ Github, PostgreSQL, Google Maps, AJAX, Geonames API, Geolocation, Geocoding, <br>jQuery, Heroku, Responsive design, Error handling forms and more.</p><hr>
<div class="about">
<h1>- Meet the It Happened Here team - </h1>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-5">
<img id="team" src="/assets/ihh-team.jpg" title="Team Photo" width="100%">
</div>
<div class="col-md-4"> <div class="text-left">
<ul>
<li><img src="/assets/ihh-logo-red.png" width="130"></li><hr>
	<li><a href="https://github.com/jenniferkwok" target="_blank"><img class="hand" src="/assets/pointingright.png" width="30">Jennifer Kwok</a></li><br>
	<li><a href="https://github.com/lauraevans99" target="_blank"><img class="hand" src="/assets/pointingright.png" width="30">Laura Evans</a></li><br>
	<li><a href="https://github.com/margauxwithanx" target="_blank"><img class="hand" src="/assets/pointingright.png" width="30">Margaux Luzuriaga</a></li><br>
	<li><a href="https://github.com/TannedAlbino" target="_blank"><img class="hand" src="/assets/pointingright.png" width="30">Uriel Chavez</a></li><br>
	<li><a href="https://github.com/laulaucia" target="_blank"><img class="hand" src="/assets/pointingright.png" width="30">Laura Buitrago</a></li>
</ul>
</div></div>
</div>
</section>

app/views/pages/community.html.erb
<style>
u2 {
font-family: 'Playfair Display', serif;
text-decoration: none;
}
</style>

<section id= "banner-paper"> 
	<h2>Community guidelines</h2>
	<div class= "container">

	<p2>It Happened Here is a community driven site and we rely on users like to add value to our site. </p2><br>
	<br>

		<u2>It Happened Here is your guide to hidden, unique and historical events in your city. Open It Happened Here on your phone and when you get close to something interesting, a clock icon will inform you of an interesting event, whether in art and culture, about people, science, politics, war or conflict, nature or sports. <br><br>


		It Happened Here can help you learn about local history and if you sign up, you can add your own events listing out your favorite places to shop, eat, and have fun. Get ready to see this world with new eyes! <br><br>


		Thank you for helping us create one of the best communities in the world,<br><br>

		
		The It Happened Here Team
		</u2>

	</div>

</section>

app/views/pages/home.html.erb
<html>
<style>
	.fa{ 
	  color: white;
	}

	.fa-close{
	  color: #A9B262;
	}
</style>
<section id= "banner"> 
<img src="/assets/ihh-logo-1-white.png" height="350"><br><b
<div class="container">
				<p>LOCATING HISTORICAL EVENTS WITHIN YOUR CITY.
				</p>
				<br>

				<% if !current_user %>
				<div class= "hvr-wobble-vertical"><a href="users/sign_up" class="btn btn-primary">SIGN UP</a></div>
				<div class= "hvr-wobble-vertical"><a href="users/sign_in" <a href="#" class="btn btn-primary">LOG IN</a></div>

				<% end %>
				<div class= "hvr-wobble-vertical"><a href="/events" class="btn btn-primary">ENTER SITE</a></div>
			</div>
	</section>
	</html>